### ISSUE TITLE
[Schema Inaccuracy] List of success response schemas lacking "required" keys

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#109]
Follow up to #106 and #107

As discussed with @xuorig I'll create separate issues for each case where the response schemas are lacking a "required" key. Some might be falso positive, I'll go through them one-by-one, but here is a list based on the latest `api.github.com.deref.json` file

126 operations are lacking "required" key in success response schemas

### Issues Created

- [x] #106  `POST /app/installations/{installation_id}/access_tokens` (`apps/create-installation-access-token`)
- [x] #107 `PUT /repos/{owner}/{repo}/contents/{path}` (`repos/create-or-update-file-contents`)
- [x] #107 `DELETE /repos/{owner}/{repo}/contents/{path}` (`repos/delete-file`)

### To be reviewed

(sorted by priority based on my best judgement)

#### apps

- [x] `GET /installation/repositories` (`apps/list-repos-accessible-to-installation`)
- [x] `GET /orgs/{org}/installations` (`orgs/list-app-installations`)
- [x] `GET /user/installations` (`apps/list-installations-for-authenticated-user`)
- [x] `GET /user/installations/{installation_id}/repositories` (`apps/list-installation-repos-for-authenticated-user`)

#### statuses and checks 

- [x] `GET /repos/{owner}/{repo}/commits/{ref}/statuses` (`repos/list-commit-statuses-for-ref`)
- [x] `POST /repos/{owner}/{repo}/statuses/{sha}` (`repos/create-commit-status`)
- [x] `PATCH /repos/{owner}/{repo}/check-suites/preferences` (`checks/set-suites-preferences`)
- [x] `GET /repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs` (`checks/list-for-suite`)
- [x] `GET /repos/{owner}/{repo}/commits/{ref}/check-suites` (`checks/list-suites-for-ref`)
- [x] `GET /repos/{owner}/{repo}/commits/{ref}/check-runs` (`checks/list-for-ref`)

#### search 

- [x] `GET /search/code` (`search/code`)
- [x] `GET /search/commits` (`search/commits`)
- [x] `GET /search/issues` (`search/issues-and-pull-requests`)
- [x] `GET /search/labels` (`search/labels`)
- [x] `GET /search/repositories` (`search/repos`)
- [x] `GET /search/topics` (`search/topics`)
- [x] `GET /search/users` (`search/users`)

#### actions 

- [x] `GET /orgs/{org}/actions/permissions` (`actions/get-github-actions-permissions-organization`)
- [x] `GET /orgs/{org}/actions/permissions/repositories` (`actions/list-selected-repositories-enabled-github-actions-organization`)
- [x] `GET /orgs/{org}/actions/permissions/selected-actions` (`actions/get-allowed-actions-organization`)
- [x] `GET /orgs/{org}/actions/runner-groups` (`actions/list-self-hosted-runner-groups-for-org`)
- [x] `POST /orgs/{org}/actions/runner-groups` (`actions/create-self-hosted-runner-group-for-org`)
- [x] `GET /orgs/{org}/actions/runner-groups/{runner_group_id}` (`actions/get-self-hosted-runner-group-for-org`)
- [x] `PATCH /orgs/{org}/actions/runner-groups/{runner_group_id}` (`actions/update-self-hosted-runner-group-for-org`)
- [x] `GET /orgs/{org}/actions/runner-groups/{runner_group_id}/repositories` (`actions/list-repo-access-to-self-hosted-runner-group-in-org`)
- [x] `GET /orgs/{org}/actions/runner-groups/{runner_group_id}/runners` (`actions/list-self-hosted-runners-in-group-for-org`)
- [x] `GET /orgs/{org}/actions/runners` (`actions/list-self-hosted-runners-for-org`)
- [x] `GET /orgs/{org}/actions/runners/downloads` (`actions/list-runner-applications-for-org`)
- [x] `GET /orgs/{org}/actions/secrets` (`actions/list-org-secrets`)
- [x] `GET /orgs/{org}/actions/secrets/{secret_name}/repositories` (`actions/list-selected-repos-for-org-secret`)
- [x] `GET /repos/{owner}/{repo}/actions/artifacts` (`actions/list-artifacts-for-repo`)
- [x] `GET /repos/{owner}/{repo}/actions/permissions` (`actions/get-github-actions-permissions-repository`)
- [x] `GET /repos/{owner}/{repo}/actions/permissions/selected-actions` (`actions/get-allowed-actions-repository`)
- [x] `GET /repos/{owner}/{repo}/actions/runners` (`actions/list-self-hosted-runners-for-repo`)
- [x] `GET /repos/{owner}/{repo}/actions/runners/downloads` (`actions/list-runner-applications-for-repo`)
- [x] `GET /repos/{owner}/{repo}/actions/runs` (`actions/list-workflow-runs-for-repo`)
- [x] `GET /repos/{owner}/{repo}/actions/runs/{run_id}/artifacts` (`actions/list-workflow-run-artifacts`)
- [x] `GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs` (`actions/list-jobs-for-workflow-run`)
- [x] `GET /repos/{owner}/{repo}/actions/runs/{run_id}/timing` (`actions/get-workflow-run-usage`)
- [x] `GET /repos/{owner}/{repo}/actions/secrets` (`actions/list-repo-secrets`)
- [x] `GET /repos/{owner}/{repo}/actions/workflows` (`actions/list-repo-workflows`)
- [x] `GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs` (`actions/list-workflow-runs`)
- [x] `GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/timing` (`actions/get-workflow-usage`)

#### notifications

- [x] `GET /notifications` (`activity/list-notifications-for-authenticated-user`)
- [x] `GET /notifications/threads/{thread_id}` (`activity/get-thread`)

#### projects 

- [x] `GET /orgs/{org}/teams/{team_slug}/projects` (`teams/list-projects-in-org`)
- [x] `GET /orgs/{org}/teams/{team_slug}/projects/{project_id}` (`teams/check-permissions-for-project-in-org`)
- [x] `POST /projects/columns/cards/{card_id}/moves` (`projects/move-card`)
- [x] `POST /projects/columns/{column_id}/moves` (`projects/move-column`)

#### git 

- [x] `POST /repos/{owner}/{repo}/git/blobs` (`git/create-blob`)
- [x] `POST /repos/{owner}/{repo}/git/commits` (`git/create-commit`)
- [x] `GET /repos/{owner}/{repo}/git/commits/{commit_sha}` (`git/get-commit`)
- [x] `GET /repos/{owner}/{repo}/git/matching-refs/{ref}` (`git/list-matching-refs`)
- [x] `GET /repos/{owner}/{repo}/git/ref/{ref}` (`git/get-ref`)
- [x] `POST /repos/{owner}/{repo}/git/refs` (`git/create-ref`)
- [x] `PATCH /repos/{owner}/{repo}/git/refs/{ref}` (`git/update-ref`)

#### enterprise

- [x] `GET /enterprises/{enterprise}/actions/permissions` (`enterprise-admin/get-github-actions-permissions-enterprise`)
- [x] `GET /enterprises/{enterprise}/actions/permissions/organizations` (`enterprise-admin/list-selected-organizations-enabled-github-actions-enterprise`)
- [x] `GET /enterprises/{enterprise}/actions/permissions/selected-actions` (`enterprise-admin/get-allowed-actions-enterprise`)
- [x] `GET /enterprises/{enterprise}/actions/runner-groups` (`enterprise-admin/list-self-hosted-runner-groups-for-enterprise`)
- [x] `POST /enterprises/{enterprise}/actions/runner-groups` (`enterprise-admin/create-self-hosted-runner-group-for-enterprise`)
- [x] `GET /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}` (`enterprise-admin/get-self-hosted-runner-group-for-enterprise`)
- [x] `PATCH /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}` (`enterprise-admin/update-self-hosted-runner-group-for-enterprise`)
- [x] `GET /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations` (`enterprise-admin/list-org-access-to-self-hosted-runner-group-in-enterprise`)
- [x] `GET /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/runners` (`enterprise-admin/list-self-hosted-runners-in-group-for-enterprise`)
- [x] `GET /enterprises/{enterprise}/actions/runners` (`enterprise-admin/list-self-hosted-runners-for-enterprise`)
- [x] `GET /enterprises/{enterprise}/actions/runners/downloads` (`enterprise-admin/list-runner-applications-for-enterprise`)
- [x] `GET /enterprises/{enterprise}/settings/billing/actions` (`billing/get-github-actions-billing-ghe`)
- [x] `GET /enterprises/{enterprise}/settings/billing/packages` (`billing/get-github-packages-billing-ghe`)
- [x] `GET /enterprises/{enterprise}/settings/billing/shared-storage` (`billing/get-shared-storage-billing-ghe`)
- [x] `GET /scim/v2/enterprises/{enterprise}/Groups` (`enterprise-admin/list-provisioned-groups-enterprise`)
- [x] `POST /scim/v2/enterprises/{enterprise}/Groups` (`enterprise-admin/provision-and-invite-enterprise-group`)
- [x] `GET /scim/v2/enterprises/{enterprise}/Groups/{scim_group_id}` (`enterprise-admin/get-provisioning-information-for-enterprise-group`)
- [x] `PUT /scim/v2/enterprises/{enterprise}/Groups/{scim_group_id}` (`enterprise-admin/set-information-for-provisioned-enterprise-group`)
- [x] `PATCH /scim/v2/enterprises/{enterprise}/Groups/{scim_group_id}` (`enterprise-admin/update-attribute-for-enterprise-group`)
- [x] `GET /scim/v2/enterprises/{enterprise}/Users` (`enterprise-admin/list-provisioned-identities-enterprise`)
- [x] `POST /scim/v2/enterprises/{enterprise}/Users` (`enterprise-admin/provision-and-invite-enterprise-user`)
- [x] `GET /scim/v2/enterprises/{enterprise}/Users/{scim_user_id}` (`enterprise-admin/get-provisioning-information-for-enterprise-user`)
- [x] `PUT /scim/v2/enterprises/{enterprise}/Users/{scim_user_id}` (`enterprise-admin/set-information-for-provisioned-enterprise-user`)
- [x] `PATCH /scim/v2/enterprises/{enterprise}/Users/{scim_user_id}` (`enterprise-admin/update-attribute-for-enterprise-user`)

#### others

- [ ] `GET /app/hook/config` (`apps/get-webhook-config-for-app`)
- [ ] `PATCH /app/hook/config` (`apps/update-webhook-config-for-app`)
- [x] `GET /emojis` (`emojis/get`)
- [x] `GET /orgs/{org}/hooks/{hook_id}/config` (`orgs/get-webhook-config-for-org`)
- [x] `PATCH /orgs/{org}/hooks/{hook_id}/config` (`orgs/update-webhook-config-for-org`)
- [x] `GET /orgs/{org}/invitations` (`orgs/list-pending-invitations`)
- [x] `POST /orgs/{org}/invitations` (`orgs/create-invitation`)
- [x] `GET /orgs/{org}/settings/billing/actions` (`billing/get-github-actions-billing-org`)
- [x] `GET /orgs/{org}/settings/billing/packages` (`billing/get-github-packages-billing-org`)
- [x] `GET /orgs/{org}/settings/billing/shared-storage` (`billing/get-shared-storage-billing-org`)
- [ ] `GET /orgs/{org}/team-sync/groups` (`teams/list-idp-groups-for-org`)
- [x] `GET /orgs/{org}/teams/{team_slug}/invitations` (`teams/list-pending-invitations-in-org`)
- [ ] `GET /orgs/{org}/teams/{team_slug}/team-sync/group-mappings` (`teams/list-idp-groups-in-org`)
- [ ] `PATCH /orgs/{org}/teams/{team_slug}/team-sync/group-mappings` (`teams/create-or-update-idp-group-connections-in-org`)
- [x] `GET /repos/{owner}/{repo}/code-scanning/alerts` (`code-scanning/list-alerts-for-repo`)
- [x] `GET /repos/{owner}/{repo}/code-scanning/alerts/{alert_number}` (`code-scanning/get-alert`)
- [x] `PATCH /repos/{owner}/{repo}/code-scanning/alerts/{alert_number}` (`code-scanning/update-alert`)
- [x] `GET /repos/{owner}/{repo}/code-scanning/analyses` (`code-scanning/list-recent-analyses`)
- [x] `GET /repos/{owner}/{repo}/commits/{commit_sha}/branches-where-head` (`repos/list-branches-for-head-commit`)
- [ ] `GET /repos/{owner}/{repo}/hooks/{hook_id}/config` (`repos/get-webhook-config-for-repo`)
- [ ] `PATCH /repos/{owner}/{repo}/hooks/{hook_id}/config` (`repos/update-webhook-config-for-repo`)
- [ ] `GET /repos/{owner}/{repo}/issues/{issue_number}/events` (`issues/list-events`)
- [ ] `GET /repos/{owner}/{repo}/issues/{issue_number}/timeline` (`issues/list-events-for-timeline`)
- [x] `GET /repos/{owner}/{repo}/keys` (`repos/list-deploy-keys`)
- [x] `POST /repos/{owner}/{repo}/keys` (`repos/create-deploy-key`)
- [x] `GET /repos/{owner}/{repo}/keys/{key_id}` (`repos/get-deploy-key`)
- [ ] `GET /repos/{owner}/{repo}/languages` (`repos/list-languages`)
- [x] `GET /repos/{owner}/{repo}/notifications` (`activity/list-repo-notifications-for-authenticated-user`)
- [x] `GET /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers` (`pulls/list-requested-reviewers`)
- [x] `GET /repos/{owner}/{repo}/stats/participation` (`repos/get-participation-stats`)
- [x] `GET /repos/{owner}/{repo}/topics` (`repos/get-all-topics`)
- [x] `PUT /repos/{owner}/{repo}/topics` (`repos/replace-all-topics`)
- [x] `GET /teams/{team_id}/invitations` (`teams/list-pending-invitations-legacy`)
- [x] `GET /teams/{team_id}/projects` (`teams/list-projects-legacy`)
- [x] `GET /teams/{team_id}/projects/{project_id}` (`teams/check-permissions-for-project-legacy`)
- [x] `GET /teams/{team_id}/team-sync/group-mappings` (`teams/list-idp-groups-for-legacy`)
- [x] `PATCH /teams/{team_id}/team-sync/group-mappings` (`teams/create-or-update-idp-group-connections-legacy`)
- [x] `GET /user/keys` (`users/list-public-ssh-keys-for-authenticated`)
- [x] `POST /user/keys` (`users/create-public-ssh-key-for-authenticated`)
- [x] `GET /user/keys/{key_id}` (`users/get-public-ssh-key-for-authenticated`)
- [x] `GET /users/{username}/settings/billing/actions` (`billing/get-github-actions-billing-user`)
- [x] `GET /users/{username}/settings/billing/packages` (`billing/get-github-packages-billing-user`)
- [x] `GET /users/{username}/settings/billing/shared-storage` (`billing/get-shared-storage-billing-user`)

**Comment by xuorig** [comment]
@gr2m I'm going through all of those, about mid way at the moment. All of those were valid so far, fixing.

Just these ones:

> POST /projects/columns/cards/{card_id}/moves (projects/move-card)
> POST /projects/columns/{column_id}/moves (projects/move-column)

These return a 201 with an empty body, I believe as expected.

**Comment by gr2m** [comment]
> I'm going through all of those

Thank you so much :) 

> Just these ones:
> 
> > POST /projects/columns/cards/{card_id}/moves (projects/move-card)
> > POST /projects/columns/{column_id}/moves (projects/move-column)
> 
> These return a 201 with an empty body, I believe as expected.

That's right, sorry!
