### ISSUE TITLE
[Schema Inaccuracy] <Describe Problem>

### ISSUE THREAD

**Issue by duythuan1234** [github/rest-api-description#3961]
# Schema Inaccuracy

## Reproduction Steps

```[tasklist]
### Tasks
- [ ] https://github.com/github/rest-api-description/pull/3959
- [ ] https://github.com/github/rest-api-description/pull/3957
- [ ] https://github.com/github/rest-api-description/pull/3955
- [ ] https://github.com/github/rest-api-description/pull/3953
```
